create table users (
    id bigint generated by default as identity primary key,
    user_code varchar(64) not null,
    display_name varchar(128) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_users_user_code unique (user_code)
);

create table groups (
    id bigint generated by default as identity primary key,
    group_code varchar(64) not null,
    group_name varchar(128) not null,
    status varchar(32) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_groups_group_code unique (group_code)
);

create table group_memberships (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    group_id bigint not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_group_memberships_user_group unique (user_id, group_id),
    constraint fk_group_memberships_user foreign key (user_id) references users (id),
    constraint fk_group_memberships_group foreign key (group_id) references groups (id)
);

create table documents (
    id bigint generated by default as identity primary key,
    group_id bigint not null,
    uploader_user_id bigint not null,
    file_name varchar(255) not null,
    file_ext varchar(16) not null,
    content_type varchar(128),
    file_size bigint not null,
    storage_bucket varchar(128) not null,
    storage_object_key varchar(512) not null,
    status varchar(32) not null,
    deleted boolean not null default false,
    failure_reason varchar(512),
    uploaded_at timestamp not null default current_timestamp,
    processed_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_documents_storage_object_key unique (storage_object_key),
    constraint fk_documents_group foreign key (group_id) references groups (id),
    constraint fk_documents_uploader foreign key (uploader_user_id) references users (id)
);

create table document_chunks (
    id bigint generated by default as identity primary key,
    document_id bigint not null,
    group_id bigint not null,
    chunk_index integer not null,
    chunk_text text not null,
    chunk_summary text,
    char_start integer,
    char_end integer,
    metadata_json jsonb,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_document_chunks_document foreign key (document_id) references documents (id),
    constraint fk_document_chunks_group foreign key (group_id) references groups (id)
);

create table ingestion_jobs (
    id bigint generated by default as identity primary key,
    document_id bigint not null,
    group_id bigint not null,
    job_type varchar(32) not null,
    status varchar(32) not null,
    retry_count integer not null default 0,
    max_retries integer not null,
    worker_id varchar(128),
    started_at timestamp,
    finished_at timestamp,
    next_retry_at timestamp,
    last_error varchar(512),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_ingestion_jobs_document foreign key (document_id) references documents (id),
    constraint fk_ingestion_jobs_group foreign key (group_id) references groups (id)
);

create index idx_group_memberships_group on group_memberships(group_id);

create index idx_documents_group on documents(group_id);
create index idx_documents_group_deleted_status on documents(group_id, deleted, status);
create index idx_documents_uploader_user on documents(uploader_user_id);

create index idx_document_chunks_document_chunk on document_chunks(document_id, chunk_index);
create index idx_document_chunks_group_document on document_chunks(group_id, document_id);

create index idx_ingestion_jobs_document on ingestion_jobs(document_id);
create index idx_ingestion_jobs_status_retry on ingestion_jobs(status, next_retry_at);
create index idx_ingestion_jobs_group_status on ingestion_jobs(group_id, status);
