alter table groups
    add column owner_user_id bigint;

update groups g
set owner_user_id = owner_membership.user_id
from (
    select group_id, min(user_id) as user_id
    from group_memberships
    group by group_id
) owner_membership
where g.id = owner_membership.group_id;

alter table groups
    alter column owner_user_id set not null,
    add constraint fk_groups_owner_user foreign key (owner_user_id) references users (id);

create index idx_groups_owner_user on groups(owner_user_id);

alter table group_memberships
    add column role varchar(32);

update group_memberships gm
set role = case
    when gm.user_id = g.owner_user_id then 'OWNER'
    else 'MEMBER'
end
from groups g
where gm.group_id = g.id;

alter table group_memberships
    alter column role set default 'MEMBER',
    alter column role set not null,
    add constraint ck_group_memberships_role check (role in ('OWNER', 'MEMBER'));

create unique index uk_group_memberships_single_owner
    on group_memberships(group_id)
    where role = 'OWNER';

create table group_invitations (
    id bigint generated by default as identity primary key,
    group_id bigint not null,
    inviter_user_id bigint not null,
    invitee_user_id bigint not null,
    status varchar(32) not null,
    decided_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint ck_group_invitations_status
        check (status in ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELED')),
    constraint fk_group_invitations_group foreign key (group_id) references groups (id),
    constraint fk_group_invitations_inviter foreign key (inviter_user_id) references users (id),
    constraint fk_group_invitations_invitee foreign key (invitee_user_id) references users (id)
);

create unique index uk_group_invitations_pending
    on group_invitations(group_id, invitee_user_id)
    where status = 'PENDING';

create index idx_group_invitations_invitee_status
    on group_invitations(invitee_user_id, status);

insert into group_invitations (
    group_id,
    inviter_user_id,
    invitee_user_id,
    status,
    created_at,
    updated_at
)
select 2002, 1002, 1001, 'PENDING', now(), now()
where exists (select 1 from groups where id = 2002)
  and exists (select 1 from users where id = 1001)
  and exists (select 1 from users where id = 1002);
