alter table documents
    add column file_hash varchar(128);

create index idx_documents_group_hash_active
    on documents (group_id, file_hash)
    where deleted = false and file_hash is not null;

create table document_upload_sessions (
    id bigint generated by default as identity primary key,
    upload_id varchar(64) not null,
    group_id bigint not null,
    uploader_user_id bigint not null,
    file_name varchar(255) not null,
    file_ext varchar(16) not null,
    content_type varchar(128) not null,
    file_size bigint not null,
    file_hash varchar(128) not null,
    chunk_size bigint not null,
    chunk_count integer not null,
    status varchar(32) not null,
    storage_bucket varchar(128) not null,
    merged_object_key varchar(512),
    expires_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint ck_document_upload_sessions_file_size_positive check (file_size > 0),
    constraint ck_document_upload_sessions_chunk_size_positive check (chunk_size > 0),
    constraint ck_document_upload_sessions_chunk_count_positive check (chunk_count > 0),
    constraint ck_document_upload_sessions_status
        check (status in ('INIT', 'UPLOADING', 'COMPLETING', 'COMPLETED', 'FAILED', 'EXPIRED')),
    constraint uk_document_upload_sessions_upload_id unique (upload_id),
    constraint fk_document_upload_sessions_group foreign key (group_id) references groups (id),
    constraint fk_document_upload_sessions_uploader foreign key (uploader_user_id) references users (id)
);

create index idx_document_upload_sessions_reusable
    on document_upload_sessions (group_id, uploader_user_id, file_hash, status, expires_at);

create table document_upload_chunks (
    id bigint generated by default as identity primary key,
    upload_id varchar(64) not null,
    chunk_index integer not null,
    chunk_size bigint not null,
    chunk_hash varchar(128) not null,
    storage_bucket varchar(128) not null,
    storage_object_key varchar(512) not null,
    uploaded_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint ck_document_upload_chunks_chunk_index_non_negative check (chunk_index >= 0),
    constraint ck_document_upload_chunks_chunk_size_positive check (chunk_size > 0),
    constraint uk_document_upload_chunks_upload_chunk unique (upload_id, chunk_index),
    constraint fk_document_upload_chunks_upload_id
        foreign key (upload_id) references document_upload_sessions (upload_id) on delete cascade
);
